# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(upload_to='')),
                ('card_id', models.IntegerField()),
            ],
        ),
    ]
