# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
