# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_auto_20170918_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ot', models.IntegerField(blank=True, null=True)),
                ('alias', models.IntegerField(blank=True, null=True)),
                ('setcode', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('def_field', models.IntegerField(blank=True, db_column='def', null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('race', models.IntegerField(blank=True, null=True)),
                ('attribute', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'datas',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('str1', models.TextField(blank=True, null=True)),
                ('str2', models.TextField(blank=True, null=True)),
                ('str3', models.TextField(blank=True, null=True)),
                ('str4', models.TextField(blank=True, null=True)),
                ('str5', models.TextField(blank=True, null=True)),
                ('str6', models.TextField(blank=True, null=True)),
                ('str7', models.TextField(blank=True, null=True)),
                ('str8', models.TextField(blank=True, null=True)),
                ('str9', models.TextField(blank=True, null=True)),
                ('str10', models.TextField(blank=True, null=True)),
                ('str11', models.TextField(blank=True, null=True)),
                ('str12', models.TextField(blank=True, null=True)),
                ('str13', models.TextField(blank=True, null=True)),
                ('str14', models.TextField(blank=True, null=True)),
                ('str15', models.TextField(blank=True, null=True)),
                ('str16', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'texts',
            },
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
