# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_auto_20171031_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.BooleanField(default=False)),
                ('hashField', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('pick', models.IntegerField()),
                ('card', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='arena.Datas')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena.Deck')),
            ],
        ),
    ]
