# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_deck_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='pick',
            new_name='draftnum',
        ),
        migrations.AddField(
            model_name='deck',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draft',
            name='picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deck',
            name='hashField',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
