# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_auto_20171109_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='text',
            field=models.ForeignKey(db_index=False, default=5, on_delete=django.db.models.deletion.CASCADE, to='arena.Texts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='draft',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
