# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0006_auto_20171114_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='hashField',
            field=models.TextField(max_length=10),
        ),
    ]
