# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0007_auto_20171129_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='mainDeck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draft',
            name='mainDeck',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
