# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0008_auto_20171202_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
