# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0009_deck_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='version',
        ),
    ]
