# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0010_remove_deck_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='bonusid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='extraDeck',
            field=models.IntegerField(default=0),
        ),
    ]
