# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0011_auto_20171207_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deckSizeid',
            field=models.IntegerField(default=0),
        ),
    ]
