# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0012_deck_decksizeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='characterid',
            field=models.IntegerField(default=0),
        ),
    ]
